knp_snappy:
    pdf:
        enabled: true
        binary: 'c:\Users\msi\Downloads\wkhtmltox-0.12.6-1.msvc2015-win64.exe'
        options:
            - { name: 'encoding', value: 'UTF-8' }
    image:
        enabled: true
        binary: 'c:\Users\msi\Downloads\wkhtmltox-0.12.6-1.msvc2015-win64.exe'
        options: []