controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_register:
  path: /inscription
  controller: App\Controller\UtilisateurController::register
